services:
  api:
    build:
      context: ./services/api
      args:
        SERVICE_PORT: ${API_PORT}
    environment:
      - SERVICE_PORT=${API_PORT}
      - BRAIN_HOST=brain
      - BRAIN_PORT=${BRAIN_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./shared:/app/shared

  brain:
    build:
      context: ./services/brain
      args:
        SERVICE_PORT: ${BRAIN_PORT}
    environment:
      - SERVICE_PORT=${BRAIN_PORT}
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=${CHROMADB_PORT}
      - CONTACTS_HOST=contacts
      - CONTACTS_PORT=${CONTACTS_PORT}
      - SUMMARIZE_HOST=summarize
      - SUMMARIZE_PORT=${SUMMARIZE_PORT}
      - SCHEDULER_HOST=scheduler
      - SCHEDULER_PORT=${SCHEDULER_PORT}
    ports:
      - "${BRAIN_PORT}:${BRAIN_PORT}"
    volumes:
      - ./shared:/app/shared

  chromadb:
    build:
      context: ./services/chromadb
      args:
        SERVICE_PORT: ${CHROMADB_PORT}
    environment:
      - SERVICE_PORT=${CHROMADB_PORT}
    ports:
      - "${CHROMADB_PORT}:${CHROMADB_PORT}"
    volumes:
      - ./shared:/app/shared

  contacts:
    build:
      context: ./services/contacts
      args:
        SERVICE_PORT: ${CONTACTS_PORT}
    environment:
      - SERVICE_PORT=${CONTACTS_PORT}
    ports:
      - "${CONTACTS_PORT}:${CONTACTS_PORT}"
    volumes:
      - ./shared:/app/shared

  imessage:
    build:
      context: ./services/imessage
      args:
        SERVICE_PORT: ${IMESSAGE_PORT}
    environment:
      - SERVICE_PORT=${IMESSAGE_PORT}
      - BLUEBUBBLES_HOST=${BLUEBUBBLES_HOST}
      - BLUEBUBBLES_PORT=${BLUEBUBBLES_PORT}
      - BLUEBUBBLES_PASSWORD=${BLUEBUBBLES_PASSWORD}
      - BRAIN_HOST=brain
      - BRAIN_PORT=${BRAIN_PORT}
    ports:
      - "${IMESSAGE_PORT}:${IMESSAGE_PORT}"
    volumes:
      - ./shared:/app/shared

  proxy:
    build:
      context: ./services/proxy
      args:
        SERVICE_PORT: ${PROXY_PORT}
    environment:
      - SERVICE_PORT=${PROXY_PORT}
      - LLM_MODEL_NAME=${LLM_MODEL_NAME}
      - OLLAMA_SERVER_HOST=${OLLAMA_SERVER_HOST}
      - OLLAMA_SERVER_PORT=${OLLAMA_SERVER_PORT}
    ports:
      - "${PROXY_PORT}:${PROXY_PORT}"
    volumes:
      - ./shared:/app/shared

  scheduler:
    build:
      context: ./services/scheduler
      args:
        SERVICE_PORT: ${SCHEDULER_PORT}
    environment:
      - SERVICE_PORT=${SCHEDULER_PORT}
    ports:
      - "${SCHEDULER_PORT}:${SCHEDULER_PORT}"
    volumes:
      - ./shared:/app/shared

  summarize:
    build:
      context: ./services/summarize
      args:
        SERVICE_PORT: ${SUMMARIZE_PORT}
    environment:
      - SERVICE_PORT=${SUMMARIZE_PORT}
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=${CHROMADB_PORT}
    ports:
      - "${SUMMARIZE_PORT}:${SUMMARIZE_PORT}"
    volumes:
      - ./shared:/app/shared

