services:
  api:
    build:
      context: ./services/api
      args:
        SERVICE_PORT: ${API_PORT}
    environment:
      - SERVICE_PORT=${API_PORT}
      - BRAIN_HOST=brain
      - BRAIN_PORT=${BRAIN_PORT}
    depends_on:
      - brain
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./services/api/app:/app/app
      - ./shared:/app/shared
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${API_PORT}/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: gelf
      options:
        gelf-address: "tcp://localhost:12201"
    networks:
      - shared-net

  brain:
    build:
      context: ./services/brain
      args:
        SERVICE_PORT: ${BRAIN_PORT}
    environment:
      - SERVICE_PORT=${BRAIN_PORT}
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=${CHROMADB_PORT}
      - CONTACTS_HOST=contacts
      - CONTACTS_PORT=${CONTACTS_PORT}
      - SUMMARIZE_HOST=summarize
      - SUMMARIZE_PORT=${SUMMARIZE_PORT}
      - SCHEDULER_HOST=scheduler
      - SCHEDULER_PORT=${SCHEDULER_PORT}
    depends_on:
      - chromadb
    ports:
      - "${BRAIN_PORT}:${BRAIN_PORT}"
    volumes:
      - ./services/brain/app:/app/app
      - ./shared:/app/shared
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BRAIN_PORT}/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: gelf
      options:
        gelf-address: "tcp://localhost:12201"
    networks:
      - shared-net

  chromadb:
    build:
      context: ./services/chromadb
      args:
        SERVICE_PORT: ${CHROMADB_PORT}
    environment:
      - SERVICE_PORT=${CHROMADB_PORT}
    ports:
      - "${CHROMADB_PORT}:${CHROMADB_PORT}"
    volumes:
      - ./services/chromadb/app:/app/app
      - ./shared:/app/shared
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${CHROMADB_PORT}/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: gelf
      options:
        gelf-address: "tcp://localhost:12201"
    networks:
      - shared-net

  contacts:
    build:
      context: ./services/contacts
      args:
        SERVICE_PORT: ${CONTACTS_PORT}
    environment:
      - SERVICE_PORT=${CONTACTS_PORT}
    ports:
      - "${CONTACTS_PORT}:${CONTACTS_PORT}"
    volumes:
      - ./services/contacts/app:/app/app
      - ./shared:/app/shared
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${CONTACTS_PORT}/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: gelf
      options:
        gelf-address: "tcp://localhost:12201"
    networks:
      - shared-net

  imessage:
    build:
      context: ./services/imessage
      args:
        SERVICE_PORT: ${IMESSAGE_PORT}
    environment:
      - SERVICE_PORT=${IMESSAGE_PORT}
      - BLUEBUBBLES_HOST=${BLUEBUBBLES_HOST}
      - BLUEBUBBLES_PORT=${BLUEBUBBLES_PORT}
      - BLUEBUBBLES_PASSWORD=${BLUEBUBBLES_PASSWORD}
      - BRAIN_HOST=brain
      - BRAIN_PORT=${BRAIN_PORT}
    depends_on:
      - brain
    ports:
      - "${IMESSAGE_PORT}:${IMESSAGE_PORT}"
    volumes:
      - ./services/imessage/app:/app/app
      - ./shared:/app/shared
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${IMESSAGE_PORT}/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: gelf
      options:
        gelf-address: "tcp://localhost:12201"
    networks:
      - shared-net

  intents:
    build:
      context: ./services/intents
      args:
        SERVICE_PORT: ${INTENTS_PORT}
    environment:
      - SERVICE_PORT=${INTENTS_PORT}
    ports:
      - "${INTENTS_PORT}:${INTENTS_PORT}"
    volumes:
      - ./services/intents/app:/app/app
      - ./shared:/app/shared
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${INTENTS_PORT}/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: gelf
      options:
        gelf-address: "tcp://localhost:12201"
    networks:
      - shared-net

  proxy:
    build:
      context: ./services/proxy
      args:
        SERVICE_PORT: ${PROXY_PORT}
    environment:
      - SERVICE_PORT=${PROXY_PORT}
      - LLM_MODEL_NAME=${LLM_MODEL_NAME}
      - OLLAMA_SERVER_HOST=${OLLAMA_SERVER_HOST}
      - OLLAMA_SERVER_PORT=${OLLAMA_SERVER_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${PROXY_PORT}:${PROXY_PORT}"
    volumes:
      - ./services/proxy/app:/app/app
      - ./shared:/app/shared
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PROXY_PORT}/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: gelf
      options:
        gelf-address: "tcp://localhost:12201"
    networks:
      - shared-net

  scheduler:
    build:
      context: ./services/scheduler
      args:
        SERVICE_PORT: ${SCHEDULER_PORT}
    environment:
      - SERVICE_PORT=${SCHEDULER_PORT}
    depends_on:
      - brain
    ports:
      - "${SCHEDULER_PORT}:${SCHEDULER_PORT}"
    volumes:
      - ./services/scheduler/app:/app/app
      - ./shared:/app/shared
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SCHEDULER_PORT}/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: gelf
      options:
        gelf-address: "tcp://localhost:12201"
    networks:
      - shared-net

  summarize:
    build:
      context: ./services/summarize
      args:
        SERVICE_PORT: ${SUMMARIZE_PORT}
    environment:
      - SERVICE_PORT=${SUMMARIZE_PORT}
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=${CHROMADB_PORT}
    depends_on:
      - brain
    ports:
      - "${SUMMARIZE_PORT}:${SUMMARIZE_PORT}"
    volumes:
      - ./services/summarize/app:/app/app
      - ./shared:/app/shared
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SUMMARIZE_PORT}/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: gelf
      options:
        gelf-address: "tcp://localhost:12201"
    networks:
      - shared-net


networks:
  shared-net:
    external: true